name: Wiki to Website Sync

on:
  gollum:  # Triggers on wiki changes
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Daily sync at midnight
  push:
    branches: ["main"]  # Also run on pushes to main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Wiki
        run: |
          git clone "https://github.com/$GITHUB_REPOSITORY.wiki.git" wiki
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install markdown-it
          npm install front-matter
          npm install fs-extra

      - name: Convert Wiki to Website
        run: node .github/scripts/convert-wiki.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
