name: Sync Wiki Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC; adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # if your wiki is added as a submodule

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # or your required Ruby version

      - name: Install dependencies
        run: bundle install

      - name: Sync Wiki Pages
        run: bundle exec rake wiki

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated wiki sync" || echo "No changes to commit"
          git push
