name: Wiki to Website Sync

on:
  gollum:  # Triggers on wiki changes
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Daily sync at midnight

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Wiki
        run: |
          git clone "https://github.com/$GITHUB_REPOSITORY.wiki.git" wiki
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install markdown-it
          npm install front-matter
          npm install fs-extra

      - name: Convert Wiki to Website
        run: node .github/scripts/convert-wiki.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
